#!/bin/sh -e
### BEGIN INIT INFO
# Provides: virtualmaster
# Required-Start:
# Required-Stop:
# Default-Start: S
# Default-Stop:
# X-Start-Before: hostname.sh networking
# Short-Description: Configures network and users on first boot of VM
### END INIT INFO
#
# Configures network and users on first boot of VM
# Main tasks are:
# - set up networking (IP, gateway, nameservers) on first booot
# - set root's password
# - optionaly create users and add ssh keys
#

case "${1}" in
	start)
		if [ -f /etc/virtualmaster.cfg ]; then
			mount -o remount,rw /
			/usr/libexec/virtualmaster-firstboot
			mount -o remount,ro / || true
		fi
		;;
esac
